# Uncomment the next line to define a global platform for your project
 platform :ios, '16.4'

target 'OpenSeaNFTsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenSeaNFTsApp
  pod 'SnapKit', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'OpenSeaNFTsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenSeaNFTsAppUITests' do
    # Pods for testing
  end

end
